added test.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,80 +1,46 @@
-name: Multi-Environment Deployment
-
 on:
-  workflow_dispatch:
   push:
     branches:
-      - feature
-      - feature/
       - main
 
+
+
 jobs:
-  deploy:
+
+  copy_variables:
     runs-on: ubuntu-latest
+
+
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: '14'
+      - name: Export GitLab Variables
+        env:
+          GITLAB_API_TOKEN: ${{ secrets.GITLAB_API_TOKEN }}
+          GITLAB_PROJECT_ID: YOUR_GITLAB_PROJECT_ID
 
-      - name: Install dependencies
-        run: npm install
-
-      - name: Deploy to Feature Environments
-        if: github.ref == 'refs/heads/main'
-        #if: startsWith(github.ref, 'refs/heads/feature')
         run: |
-          echo 'hello world'
-          # Add commands to deploy to feature environments
-
-      - name: Deploy to Release Environments
-        if: github.ref == 'refs/heads/main'
-        #if: startsWith(github.ref, 'refs/heads/feature')
-        run: |
-          # Add commands to deploy to release environments
-          echo 'hello'
-
-      - name: Deploy to Master Environments
-        if: github.ref == 'refs/heads/feature'
-        #if: startsWith(github.ref, 'refs/heads/main') && github.event_name == 'workflow_dispatch'
-        run: |
-          # Add commands to deploy to master environments
-          echo 'hi'
-
-  deploy2:
-    runs-on: ubuntu-latest
-    if: github.ref == 'refs/heads/feature'
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Set up Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: '14'
-
-      - name: Install dependencies
-        run: npm install
-
-      - name: Deploy to Feature Environments
-        if: startsWith(github.ref, 'refs/heads/feature')
-        run: |
-          echo 'hello world'
-          # Add commands to deploy to feature environments
-
-      - name: Deploy to Release Environments
-        if: startsWith(github.ref, 'refs/heads/feature/***')
-        run: |
-          # Add commands to deploy to release environments
-          echo 'hello'
-
-      - name: Deploy to Master Environments
-        if: github.ref == 'refs/heads/main'
-        run: |
-          # Add commands to deploy to master environments
-          echo 'hi'
+          #while IFS=' ' read -r project_name project_id; do
+          #token="${{ secrets.HUB_PERSONAL_ACCESS_TOKEN }}"
+          PRIVATE_TOKEN="${{ secrets.GITLAB_TOKEN }}"
+          #response_code=$(curl -w "%{http_code}\n" -o response.json -X POST -H "Authorization: Bearer $token" -H "Accept: application/vnd.github.v3+json" -d '{"name": "'"$project_name"'", "private": true}' https://api.github.com/orgs/BritishAirways-Ent/repos)
+          #response_code=$(curl -w "%{http_code}\n" -o response.json --request POST --header "PRIVATE-TOKEN:$PRIVATE_TOKEN" --header "Content-Type:application/json" --data '{"url":"https://n509249:'"$token"'@github.com/BritishAirways-Ent/'"$project_name"'.git","enabled": true}'  https://gitlab.com/api/v4/projects/$project_id/remote_mirrors)
+          response_code=$(curl -w "%{http_code}\n" -o response.json --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" "https://gitlab.com/api/v4/projects/32754322/variables")
+          echo $response.json
+          response_body=$(jq '.' response.json)
+                if [[ "$(echo "$response_code")" -ne 201 ]]; then
+                  isError=true
+                  echo "PROJECT ID:" $projectid
+                  echo "ERROR CODE:" $response_code
+                  echo "ERROR MESSAGE:" $response_body
+                fi
+          if [[ "$isError" = true ]]; then
+                       exit 1
+          fi
+          #done <project_name_url.txt
+          # Use the GitLab API to fetch your variables
+          # Replace 'YOUR_GITLAB_PROJECT_ID' with your GitLab project ID
+          #curl --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
+          #"https://gitlab.example.com/api/v4/projects/$GITLAB_PROJECT_ID/variables" \| jq -r '.[] | "echo ::set-env name=\(.key)::\(.value)"'
